In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'best'}: 0.8787387174797947

In [15]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[80  5]
 [11 38]]

In [16]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.88      0.94      0.91        85
           1       0.88      0.78      0.83        49

    accuracy                           0.88       134
   macro avg       0.88      0.86      0.87       134
weighted avg       0.88      0.88      0.88       134

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.858343337334934

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003903,0.002950,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.002794,0.001517,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.004435,0.001163,0.007743,0.001752,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.849794,0.866968,0.775815,0.886792,0.849057,0.845685,0.037558,3
3,0.004916,0.001078,0.011679,0.002788,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.885356,0.815037,0.756031,0.868632,0.865054,0.838022,0.047242,5
4,0.004076,0.001087,0.011549,0.003727,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.804764,0.886792,0.796284,0.867097,0.905069,0.852001,0.043796,2
5,0.004989,0.000734,0.013049,0.001673,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.829615,0.850809,0.735849,0.888646,0.783837,0.817751,0.053137,8
6,0.001695,0.001275,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001730,0.000896,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.006023,0.000988,0.010139,0.002416,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.829615,0.866968,0.756031,0.906166,0.903610,0.852478,0.055734,1
9,0.003837,0.001783,0.006983,0.001163,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.887346,0.793754,0.833323,0.783837,0.903610,0.840374,0.048218,4
10,0.003849,0.001436,0.007885,0.002047,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.808927,0.828959,0.814409,0.813179,0.905069,0.834109,0.036117,6
11,0.003869,0.000950,0.007070,0.000674,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.829615,0.850809,0.740173,0.869709,0.805463,0.819154,0.044928,7

In [20]:
age_input=float(input("Age:"))
EstimatedSalary_input = float(input("EstimatedSalary: "))
Gender_Male = int(input("Gender_Male (1=Male, 0=Female): "))

Age: 45
EstimatedSalary:  500000
Gender_Male (1=Male, 0=Female):  0

In [23]:
new_data = [[age_input, EstimatedSalary_input, Gender_Male]]
new_data_scaled = sc.transform(new_data)

In [24]:
new_data_scaled

array([[ 0.71340608, 12.79103885, -0.99250926]])

In [25]:
Future_Prediction = grid.predict(new_data_scaled)
print("Future_Prediction = {}".format(Future_Prediction[0]))

Future_Prediction = 1