In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
print(np.__version__)

2.3.5

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [5]:
dataset.head(133)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [6]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [8]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [9]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test_) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions) 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9108102345415777

In [16]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002077,0.000595,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.001899,0.000222,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.038951,0.003256,0.012658,0.002870,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.600000,0.742857,0.790698,0.900000,0.888889,0.784489,0.109590,8
3,0.322241,0.020580,0.017747,0.002687,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.764706,0.842105,0.809524,0.926829,0.923077,0.853248,0.063507,4
4,0.032226,0.001712,0.007284,0.000354,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.800000,0.789474,0.809524,0.926829,0.894737,0.844113,0.055736,5
5,0.273469,0.023505,0.015299,0.001766,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.800000,0.871795,0.809524,0.900000,0.947368,0.865737,0.055418,1
6,0.001121,0.000329,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001494,0.001019,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.033968,0.007064,0.008168,0.001933,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.727273,0.777778,0.809524,0.900000,0.918919,0.826699,0.072734,7
9,0.273877,0.011990,0.013638,0.001214,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.800000,0.842105,0.809524,0.926829,0.947368,0.865165,0.060719,2
10,0.031357,0.002431,0.007478,0.001183,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.764706,0.810811,0.809524,0.871795,0.923077,0.835982,0.055285,6
11,0.249766,0.012711,0.013921,0.001285,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.800000,0.871795,0.809524,0.900000,0.923077,0.860879,0.048707,3

In [19]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[78  7]
 [ 5 44]]

In [20]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93        85
           1       0.86      0.90      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.91      0.90       134
weighted avg       0.91      0.91      0.91       134

table_pr=pd.DataFrame()

In [21]:
print(X_test)

     Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
168   29           148000            1
150   26            15000            0
393   60            42000            1
66    24            19000            1
240   42           149000            1

[134 rows x 3 columns]

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.49039615846338536

In [23]:
age_input = float(input("Age: "))
EstimatedSalary_input = float(input("EstimatedSalary: "))
Gender_Male = int(input("Gender_Male (1=Male, 0=Female): "))

Age:  64
EstimatedSalary:  200000
Gender_Male (1=Male, 0=Female):  0

In [24]:
new_data = [[age_input, EstimatedSalary_input, Gender_Male]]
new_data_scaled = sc.transform(new_data)

In [25]:
new_data_scaled

array([[ 2.58739483,  3.8813132 , -0.99250926]])

In [26]:
Future_Prediction = grid.predict(new_data_scaled)
print("Future_Prediction = {}".format(Future_Prediction[0]))

Future_Prediction = 1